export const actionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    ACTIVE_PRODUCT: 'ACTIVE_PRODUCT',
    REMOVE_ACTIVE_PRODUCT: 'REMOVE_ACTIVE_PRODUCT',
    SHOW_CART: 'SHOW_CART',
    REMOVE_CART: 'REMOVE_CART',
    ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
    REMOVE_ALL_PRODUCTS_FROM_CART: 'REMOVE_ALL_PRODUCTS_FROM_CART',
    REMOVE_PRODUCT_FROM_CART: 'REMOVE_PRODUCT_FROM_CART',
    FILTER_PRODUCTS: 'FILTER_PRODUCTS',
    CLEAR_FILTERS: 'CLEAR_FILTERS'
}
